name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 13

    # Runs a set of commands using the runners shell
    - name: Run build
      run: |
        npm install
        npm run build
